# site settings
title: Cryptoeconomics
subtitle: Moscow meetup
email: gershuni.stepan@gmail.com
description: CryptoEcon Moscow Meetup website
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 2

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
